### ISSUE TITLE
mpmath and math make different result

### ISSUE THREAD

**Issue by retsyo** [fredrik-johansson/mpmath#363]
math.cos gives wrong answer.

```python
import math
import mpmath

print(mpmath.__version__)

f = lambda x: x*mpmath.cos(x)
fact = mpmath.taylor(f, 0, 9)

print(fact)
print([mpmath.identify(i) for i in fact])
print('\n')


g = lambda x: x*math.cos(x)
fact = mpmath.taylor(g, 0, 9)

print(fact)
print([mpmath.identify(i) for i in fact])
```
says
```bash
[mpf('0.0'), mpf('1.0'), mpf('0.0'), mpf('-0.5'), mpf('0.0'), mpf('0.041666666666666664'), mpf('0.0'), mpf('-0.0013888888888888889'), mpf('0.0'), mpf('2.4801587301587302e-5')]
['0', '1', '0', '-((1/2))', '0', '(1/24)', '0', '-((1/720))', '0', '1/(2**7*3**2*5*7)']


[mpf('0.0'), mpf('1.0'), mpf('0.0'), mpf('0.0'), mpf('0.0'), mpf('0.0'), mpf('0.0'), mpf('0.0'), mpf('0.0'), mpf('0.0')]
['0', '1', '0', '0', '0', '0', '0', '0', '0', '0']
```

**Comment by warnerjon12** [comment]
The issue is that in the `hsteps` method, math.cos returns zero, whereas mpmath.cos returns a small number, considered to be nonzero. To illustrate, here is a list of `nstr(ctx.difference(y, k))` for each iteration with mpmath.cos:

`['2.1684e-19', '1.22349e-55', '-3.05874e-56', '-7.19105e-93', '2.39702e-93', '3.1558e-130', '-1.5779e-130', '-9.53905e-168', '9.53905e-168']`

with math.cos, these are all zero. This data is computed from `hsteps`, so the issue is that `hsteps` is generating numbers too small for double precision. This is not a problem for mpmath.cos.

**Comment by warnerjon12** [comment]
I will make a pull request later that helps with this issue (basically I added a check so that all positive and negative values get added separately until the end). It still fails for math.cos, but there is not much else to do.

**Comment by fredrik-johansson** [comment]
Not a bug, as explained above.
