### ISSUE TITLE
fnan and float('nan') behaves differently with math.copysign

### ISSUE THREAD

**Issue by bjodah** [fredrik-johansson/mpmath#383]
Consider this:
```python
>>> import math
>>> from mpmath.libmp.libmpf import fnan
>>> from mpmath.libmp import to_float
>>> math.copysign(1.0, to_float(fnan))
-1.0
>>> math.copysign(1.0, float('nan'))
1.0
```
I would have expected `fnan` and `float('nan')` to behave in the same way here.

This C program:
```C
#include <math.h>
#include <stdio.h>

int main(){
    double result = copysign(1.0, NAN);
    printf("%f", result);
    return 0;
}
```
gives:
```shell
$ ./a.out
1.000000
```

This came up in sympy/sympy#14010

**Comment by warnerjon12** [comment]
Since the sign bit for NaNs is not specified by IEEE 754, you cannot expect consistent behavior when copying the sign of NaNs in general. However, I can change the `fnan` representation to match that of the platform's `float('nan')`. Note that the second result could have been -1 as well on a different platform.

**Comment by bjodah** [comment]
I see, thanks. If it's undefined behavior I suppose there is no need to enforce the same result.
