### ISSUE TITLE
nstr() and nprint() do not correctly round after 500+ digits

### ISSUE THREAD

**Issue by shippert** [fredrik-johansson/mpmath#389]
Stock mpmath in Python 3, running Linux Mint 18.1 and 17.

nstr() normally rounds the final digit of a repeating decimal, so by default the last displayed digit of (e.g.) 2/3 should always 7.  But if you set n=500+, it does not correctly round, and instead shows a 6.  (For n < 500, it rounds up correctly.)

```
>>> import mpmath as mp
>>> mp.mp.dps = 2000
>>> rat=mp.fdiv(2,3)
>>> mp.nprint(rat,499)
0.6666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666667
>>> mp.nprint(rat,500)
0.66666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666

```

**Comment by warnerjon12** [comment]
This is simply the result of rounding by truncation, which comes up naturally at a couple of points in the calculation. I don't consider this a really big issue, since such truncation rounding is only going to cost you at most one digit difference. Even converting to a million digit string, the last digit is still 6. I recommend that you close this issue, we have much more important issues to deal with than loss of one decimal place when printing, especially since you usually print much less than you store.

**Comment by asmeurer** [comment]
I don't understand why you think it should be closed. The point of nprint is to give `n` digits of the number, rounded correctly. Do you think the user should be responsible for computing enough digits of the expression and rounding himself? 

Also, one issue being open does not "deprioritize" the others, as the project is open source and all work is done on a volunteer basis anyway (i.e., people work on what they want to work on).

**Comment by fredrik-johansson** [comment]
Yes, this is a bug. Note that mpmath doesn't actually guarantee correct rounding, but this is gratuitously incorrect.

The offending code in to_str checks if dps < 500 and only rounds up in this case in order to avoid an extra decimal->binary->decimal roundtrip which can be expensive. The better solution when the numbers get large would be to round up directly in the decimal string.

**Comment by asmeurer** [comment]
> Note that mpmath doesn't actually guarantee correct rounding

Regarding this, does it guarantee correct rounding if said rounding can be determined with the given `dps` (here 2000), or even then is it not always guaranteed?

**Comment by fredrik-johansson** [comment]
No.
