### ISSUE TITLE
A case with accuracy significantly less than precision for rf

### ISSUE THREAD

**Issue by oscarbenjamin** [fredrik-johansson/mpmath#421]
This is from [https://github.com/sympy/sympy/issues/15575](https://github.com/sympy/sympy/issues/15575).

Mpmath's `rf` function in this particular case seems to give an accuracy significantly less than the requested precision:
```julia
In [1]: from mpmath import mp                                                                                                     

In [2]: x = mp.mpf('-255.5815971722918')                                                                                          

In [3]: k = mp.mpf('-0.5119253100282322')                                                                                         

In [4]: v1 = mp.rf(x, k)                                                                                                          

In [5]: v1                                                                                                                        
Out[5]: mpf('-0.19527202788048453')

In [6]: mp.dps = 16                                                                                                               

In [7]: v2 = mp.rf(x, k)                                                                                                          

In [8]: v2                                                                                                                        
Out[8]: mpf('-0.1952720278805729487')

In [9]: v1 - v2                                                                                                                   
Out[9]: mpf('8.841538612358590399e-14')
```

I don't know much about this function, just forwarding this from sympy.

**Comment by WarrenWeckesser** [comment]
This is the definition of `ff` from `factorials.py`:
```
@defun
def rf(ctx, x, n):
    return ctx.gammaprod([x+n], [x])
```
For the values given (no poles or zeros), `gammaprod([a], [b])` does, in effect, this:

```
p = mp.one
mp.prec += 15
p *= mp.gamma(a)
p /= mp.gamma(b)
mp.prec -= 15
```
The problem is that the argument `a = x + k` is computed *before* the precision is increased.

Here's a complete script to demonstrate the problem:
```
from mpmath import mp

x = mp.mpf('-255.5815971722918')
k = mp.mpf('-0.5119253100282322') 

v1 = mp.rf(x, k)
print(v1)

v2 = mp.one
num = x + k
mp.prec += 15
v2 *= mp.gamma(num)
v2 /= mp.gamma(x)
mp.prec -= 15

print(v2)

v3 = mp.one
mp.prec += 15
num = x + k
v3 *= mp.gamma(num)
v3 /= mp.gamma(x)
mp.prec -= 15

print(v3)
```
Output:
```
-0.195272027880485
-0.195272027880485
-0.195272027880573
```
The third value is the correct value, computed by computing `x + k` after increasing the precision.

**Comment by WarrenWeckesser** [comment]
Several other functions that sum their arguments before passing them to `gammaprod` have the same problem.  For example, `beta`:

```
In [238]: x = mp.mpf('123.4567890123456')

In [239]: y = mp.mpf('0.01234567890123456')

In [240]: mp.dps = 15

In [241]: v1 = mp.beta(x, y); v1
Out[241]: mpf('75.79570697965822')

In [242]: mp.dps = 16

In [243]: v2 = mp.beta(x, y); v2
Out[243]: mpf('75.79570697966081738')

In [244]: v2 - v1
Out[244]: mpf('2.597033699203166179e-12')

In [245]: (v2 - v1)/v2
Out[245]: mpf('3.426359885923433345e-14')
```
The relative error in that last line is bigger than expected.

**Comment by WarrenWeckesser** [comment]
@fredrik-johansson, do you consider this issue a bug?  If so, is changing `rf` from

```
def rf(ctx, x, n):
    return ctx.gammaprod([x+n], [x])
```
to
```
def rf(ctx, x, n):
    return ctx.gammaprod([ctx.fadd(x, n, prec=ctx.prec+15)], [x])
```
a reasonable way to fix it?

When I make this change, `v1 = mp.rf(x, k)` in the above examples is computed to the expected precision.  I increment the precision in `fadd` by 15 because that is the same increment used internally in `gammaprod`.

If this is a correct fix, it will need to be done wherever an argument to `gammaprod` is an expression rather than a single name.  For example, `beta` uses the expression `ctx.gammaprod([x, y], [x+y])`, and `ff` has `ctx.gammaprod([x+1], [x-n+1])`.

And that is just `gammaprod`.  Presumably the same issue occurs whenever an expression is used as the argument to a function that uses increased precision internally.

**Comment by fredrik-johansson** [comment]
Sure. Just to be clear, this is not an isolated problem, and it's not an oversight either. Loss of precision occurs basically any time functions are composed in any way (i.e. almost everywhere in mpmath). Writing the code to increment the precision correctly in every case is simply not realistic, at least without something automatic like ball arithmetic. But we can still put in such code where it is natural and convenient, and this is a good example. Of course 15 bits is not always enough; to ensure that the rising factorial is computed accurately in all cases, the actual condition number of the gamma function has to be bounded. That's slightly overkill, though; we could be lazy and just put in `10*ctx.prec` or even `100*ctx.prec` here (since it's just for one addition, it doesn't matter if the precision is outrageous)...

**Comment by fredrik-johansson** [comment]
Worked around.
