### ISSUE TITLE
Is there a way of identifying lowest/greatest positive numbers given current precision?

### ISSUE THREAD

**Issue by KShutter** [fredrik-johansson/mpmath#452]
In what regards `mp.mpf`, is there a way to retrieve what are, at the currently specified precision, the:

(a) epsilon, i.e. the lowest positive number the system recognizes as being greater than zero;
(b) the greatest positive number before positive infinity?

Those are useful, for example, when one needs to implement a more complicated while-loop that goes until "convergence" or when one wants to avoid division by zero.

**Comment by fredrik-johansson** [comment]
There are no such numbers. Exponents can be arbitrarily large or small.

**Comment by KShutter** [comment]
@fredrik-johansson Thanks for your quick reply. I understand that `mpmath` can be used with arbitrarily small exponents. But isn't it true that **for a given, chosen precision level,** there is a minimum/maximum number of exponents that can be reached before a numbers is indistinguishable from zero/infinity?

**Comment by asmeurer** [comment]
@KShutter no, even for a fixed precision this is the case. See http://mpmath.org/doc/1.1.0/technical.html#representation-of-numbers. This is because unlike some arbitrary precision libraries, which restrict exponents to 32-bit or 64-bit signed ints, mpmath uses bigints (Python integers) for the exponents. You can see for yourself that something like `mpmath.mpf('1e-10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000')` works just fine. Check the `_mpf_` attribute of that object to see the exponent that is stored. The exponent size is only limited by what can fit in memory.

**Comment by KShutter** [comment]
@asmeurer  Oh, I see, thanks! So, I think my problem becomes how to stop an algorithm that sums to infinity or a denominator that approaches zero, in the context of `mpmath`. But I guess the right thing for me to do then is to close this issue and open a new, proper one.
